apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinelops
  labels:
    {{- include "sentinelops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sentinelops
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sentinelops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: sentinelops
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SENTINELOPS_LLM_PROVIDER
              value: bedrock
            - name: SENTINELOPS_BEDROCK_MODEL_ID
              value: {{ .Values.bedrock.modelId | quote }}
            - name: AWS_REGION
              value: {{ .Values.bedrock.region | quote }}
            {{ if .Values.persistence.dynamodbTable }}
            - name: SENTINELOPS_DYNAMODB_TABLE
              value: {{ .Values.persistence.dynamodbTable | quote }}
            {{ end }}
            {{ if .Values.persistence.runbooksBucket }}
            - name: SENTINELOPS_RUNBOOKS_BUCKET
              value: {{ .Values.persistence.runbooksBucket | quote }}
            {{ end }}
            {{ if .Values.tracing.otlpEndpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.tracing.otlpEndpoint | quote }}
            {{ end }}
            - name: SENTINELOPS_APPROVAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: sentinelops-approval
                  key: secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: sentinelops
